### PR TITLE
(ref + fix): Moving ZeSlotConfiguration persistence logic to a repository

### LINKED ISSUE #395: Reset slot configuration does not work
**Describe the bug**
When trying to reset a slot configuration, nothing happens.

**To Reproduce**
1. Open the app;
2. Edit a slot;
3. Save the changes;
4. Click on the reset button;
5. Nothing happens.

**Expected behavior**
- The slot should configuration should be reset to the default configuration;
- Default configuration definition is the one when you open the app for the very first time (clean data).

**Screenshots**

https://github.com/user-attachments/assets/c366717d-03f5-4ba4-8f6e-4b50804655e8

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by lucasvillaverde**
## Summary

- Extracting the logic from `ZePersistence`, which handled theme, open api and zeslot rules to a `ZeSlotRepository`;
- With this approach we can use this repository across screens and possibly detach current features to use their own VM (such as the simulator screen);
- Also enables (if needed) to change how the data is retrieved, we can change it to a flow and shift to observable pattern for example;
- As a bonus, this fixes Fixes #395, since it enables us to add and remove previously saved configurations.

## Screenshot/Gif

| Reset fix | Overall behavior |
| ---- | ----- |
| <video src=https://github.com/user-attachments/assets/98f28b3a-3fc1-44f9-b2c3-c7991f8fe905 /> | <video src=https://github.com/user-attachments/assets/cc71cf9d-cce4-4efa-8cb9-7b16e867d514 /> |

<details>

<summary>Screenshot Name</summary>

</details>

### CODE REVIEW

File: zeapp/android/src/main/java/de/berlindroid/zeapp/zevm/ZeBadgeViewModel.kt [hunk 1]
```diff
@@ -363,78 +356,24 @@ class ZeBadgeViewModel
...
+                // Removing all the saved data from the persistence
+                zeSlotRepository.removeSlotConfiguration(slot = slot)
+                // Getting the default value
+                val defaultSlotConfiguration = zeSlotRepository.getDefaultSlotConfiguration(slot = slot)
+
                 _uiState.update {
                     it.copy(
                         message = "",
-                        slots = it.slots.copy(slot to initialConfiguration(slot)),
+                        slots = it.slots.copy(slot to defaultSlotConfiguration),
```
Comment (lucasvillaverde) [inline zeapp/android/src/main/java/de/berlindroid/zeapp/zevm/ZeBadgeViewModel.kt:367]: this fixes #395

File: zeapp/android/src/main/java/de/berlindroid/zeapp/zevm/ZeBadgeViewModel.kt [hunk 2]
```diff
@@ -363,78 +356,24 @@ class ZeBadgeViewModel
...
-                    )
-
-                ZeSlot.Camera ->
-                    ZeConfiguration.Camera(
-                        imageProviderService.provideImageBitmap(R.drawable.soon),
-                    )
-            }
+            // try to get from the persistence, if not present, return the default
+            return zeSlotRepository.getSlotConfiguration(slot = slot)
+                ?: zeSlotRepository.getDefaultSlotConfiguration(slot = slot)
```
Comment (lucasvillaverde) [inline zeapp/android/src/main/java/de/berlindroid/zeapp/zevm/ZeBadgeViewModel.kt:376]: Now the initial configuration is a bit easier to understand.
We basically check if the configuration is present, if not, default to default.

File: zeapp/android/src/main/java/de/berlindroid/zeapp/zerepositories/ZeSlotRepository.kt [hunk 3]
```diff
@@ -0,0 +1,309 @@
...
+                    )
+            }
+
+        fun getInitialSlots(): List<ZeSlot> =
+            listOf(
+                ZeSlot.Name,
+                ZeSlot.FirstSponsor,
+                ZeSlot.Camera,
+                ZeSlot.Add,
+            )
```
Comment (lucasvillaverde) [inline zeapp/android/src/main/java/de/berlindroid/zeapp/zerepositories/ZeSlotRepository.kt:156]: Not sure if this is the best place for this method to be, but other than that, this will allow us to decouple other functionalities that were attached to the `ZeBadgeViewModel`, for example, now the **simulator** can access this repository, and have its own `ViewModel`.

Comment (mariobodemann) [reply zeapp/android/src/main/java/de/berlindroid/zeapp/zerepositories/ZeSlotRepository.kt:161]: I like that, at some point we should also think about decoupling the name from the configuration and make the add configuration (????) actually a thing not a configuration.... Anyway, good approach really like the separation.

Comment (lucasvillaverde) [reply zeapp/android/src/main/java/de/berlindroid/zeapp/zerepositories/ZeSlotRepository.kt:161]: Yeah, definitelly! I'm still struggling a bit to understand that a slot refers to a configuration and not "have" a configuration as an attribute on a single entity.
But agree with future decoupling work.
